# Generated by Django 3.1.2 on 2021-02-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='txn_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
