# Generated by Django 3.1.2 on 2021-02-19 08:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0004_auto_20210211_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='isAnExpense',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
