# Generated by Django 3.1.2 on 2021-02-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_transaction_isanexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='isAnExpense',
            field=models.CharField(max_length=5),
        ),
    ]
