# Generated by Django 3.1.2 on 2021-02-19 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_auto_20210219_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='isAnExpense',
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='isAnExpense',
            field=models.CharField(default=django.utils.timezone.now, max_length=5),
            preserve_default=False,
        ),
    ]
